### ISSUE TITLE
Is it possible to convert slob format into aar?

### ISSUE THREAD

**Issue by slycelote** [aarddict/tools#40]
Software I use (GoldenDict on desktop and Aard 1 on android) supports only aar files. The link to aar dictionaries (http://aarddict.org/1/) is always down, and there are more dictionaries in slob format anyway. Is it possible to convert them into the old version (maybe even with loss of some data that is unsupported in the old format)?

**Comment by itkach** [comment]
> Is it possible to convert them into the old version

If somebody decides to write converter to do so. Not likely to happen. 

> The link to aar dictionaries (http://aarddict.org/1/) is always down

There's DNS configuration issue at the moment, hopefully the site will be back online soon. 

> Software I use (GoldenDict on desktop and Aard 1 on android) supports only aar files.

My impression was that GoldenDict added slob format support a while ago. Are you sure it only supports aar files?

**Comment by slycelote** [comment]
> My impression was that GoldenDict added slob format support a while ago.

Yes, but my repositories have an older version.

> There's DNS configuration issue at the moment, hopefully the site will be back online soon. 

Thanks, I'm looking forward to it.
